nelmio_api_doc:
    documentation:
        info:
            title: API de Gesti칩n de Proyectos
            description: Documentaci칩n de la API REST del sistema de gesti칩n de tareas y proyectos.
            version: 1.0.0
            contact:
                name: 'Isaac Ignacio Antu침a Rengifo'
                email: 'iantunarengifo@gmail.com'
    areas:
        default:
            path_patterns: [ ^/api ]
    html_config:
        assets_mode: cdn



